import type { Product } from "./types"

// Helper function to create placeholder image URLs with specific categories
function getPlaceholderImage(category: string, id: number): string {
  const categories: Record<string, string> = {
    Kitchen: "kitchen",
    Bathroom: "bathroom",
    Clothing: "clothing",
    Accessories: "accessories",
    Electronics: "electronics",
    Home: "home",
    Beauty: "beauty",
    Fitness: "fitness",
    Garden: "garden",
    Office: "office",
    Pets: "pets",
    Kids: "kids",
  }

  const categorySlug = categories[category] || "eco"
  return `https://source.unsplash.com/random/400x300/?${categorySlug},sustainable&sig=${id}`
}

export const products: Product[] = [
  // Kitchen Products
  {
    id: "1",
    name: "Bamboo Water Bottle",
    description:
      "Eco-friendly bamboo water bottle with stainless steel interior. Keeps drinks cold for 24 hours and hot for 12 hours.",
    price: 24.99,
    image: getPlaceholderImage("Kitchen", 1),
    category: "Kitchen",
    tags: ["bamboo", "water bottle", "reusable"],
    inStock: true,
  },
  {
    id: "2",
    name: "Organic Cotton T-Shirt",
    description: "100% organic cotton t-shirt made with sustainable farming practices and eco-friendly dyes.",
    price: 29.99,
    image: getPlaceholderImage("Clothing", 2),
    category: "Clothing",
    tags: ["organic", "cotton", "t-shirt"],
    inStock: true,
  },
  {
    id: "3",
    name: "Recycled Plastic Backpack",
    description: "Stylish backpack made from recycled ocean plastic. Durable, waterproof, and eco-friendly.",
    price: 59.99,
    image: getPlaceholderImage("Accessories", 3),
    category: "Accessories",
    tags: ["recycled", "backpack", "ocean plastic"],
    inStock: true,
  },
  {
    id: "4",
    name: "Solar Powered Charger",
    description:
      "Portable solar charger for all your devices. Eco-friendly way to keep your electronics charged on the go.",
    price: 45.99,
    image: getPlaceholderImage("Electronics", 4),
    category: "Electronics",
    tags: ["solar", "charger", "portable"],
    inStock: true,
  },
  {
    id: "5",
    name: "Beeswax Food Wraps",
    description: "Reusable food wraps made from organic cotton and beeswax. A sustainable alternative to plastic wrap.",
    price: 18.99,
    image: getPlaceholderImage("Kitchen", 5),
    category: "Kitchen",
    tags: ["beeswax", "food wrap", "reusable"],
    inStock: true,
  },
  {
    id: "6",
    name: "Bamboo Toothbrush Set",
    description: "Set of 4 biodegradable bamboo toothbrushes with charcoal-infused bristles.",
    price: 12.99,
    image: getPlaceholderImage("Bathroom", 6),
    category: "Bathroom",
    tags: ["bamboo", "toothbrush", "biodegradable"],
    inStock: true,
  },
  {
    id: "7",
    name: "Reusable Produce Bags",
    description: "Set of 5 mesh produce bags made from recycled materials. Perfect for grocery shopping.",
    price: 14.99,
    image: getPlaceholderImage("Kitchen", 7),
    category: "Kitchen",
    tags: ["produce bags", "reusable", "recycled"],
    inStock: true,
  },
  {
    id: "8",
    name: "Eco-Friendly Yoga Mat",
    description: "Yoga mat made from natural rubber and recycled materials. Non-toxic and biodegradable.",
    price: 49.99,
    image: getPlaceholderImage("Fitness", 8),
    category: "Fitness",
    tags: ["yoga", "mat", "natural rubber"],
    inStock: true,
  },
  // Additional Kitchen Products
  {
    id: "9",
    name: "Stainless Steel Straw Set",
    description: "Set of 8 reusable stainless steel straws with cleaning brush and carrying pouch.",
    price: 15.99,
    image: getPlaceholderImage("Kitchen", 9),
    category: "Kitchen",
    tags: ["straws", "stainless steel", "reusable"],
    inStock: true,
  },
  {
    id: "10",
    name: "Bamboo Cutting Board",
    description: "Durable bamboo cutting board that's naturally antibacterial and water-resistant.",
    price: 29.99,
    image: getPlaceholderImage("Kitchen", 10),
    category: "Kitchen",
    tags: ["bamboo", "cutting board", "kitchen"],
    inStock: true,
  },
  {
    id: "11",
    name: "Silicone Food Storage Bags",
    description: "Reusable silicone food storage bags that are dishwasher, microwave, and freezer safe.",
    price: 19.99,
    image: getPlaceholderImage("Kitchen", 11),
    category: "Kitchen",
    tags: ["silicone", "food storage", "reusable"],
    inStock: true,
  },
  {
    id: "12",
    name: "Compostable Dish Sponges",
    description: "Pack of 4 plant-based, compostable dish sponges that clean effectively without microplastics.",
    price: 9.99,
    image: getPlaceholderImage("Kitchen", 12),
    category: "Kitchen",
    tags: ["compostable", "sponges", "cleaning"],
    inStock: true,
  },
  // Bathroom Products
  {
    id: "13",
    name: "Shampoo Bar",
    description: "Zero-waste shampoo bar with natural ingredients. Equivalent to 3 bottles of liquid shampoo.",
    price: 12.99,
    image: getPlaceholderImage("Bathroom", 13),
    category: "Bathroom",
    tags: ["shampoo", "zero waste", "plastic free"],
    inStock: true,
  },
  {
    id: "14",
    name: "Organic Cotton Towel Set",
    description: "Set of 4 organic cotton towels. Soft, absorbent, and free from harmful chemicals.",
    price: 39.99,
    image: getPlaceholderImage("Bathroom", 14),
    category: "Bathroom",
    tags: ["towels", "organic cotton", "bathroom"],
    inStock: true,
  },
  {
    id: "15",
    name: "Biodegradable Dental Floss",
    description: "Compostable dental floss made from corn starch with a refillable glass container.",
    price: 8.99,
    image: getPlaceholderImage("Bathroom", 15),
    category: "Bathroom",
    tags: ["dental", "biodegradable", "zero waste"],
    inStock: true,
  },
  {
    id: "16",
    name: "Safety Razor",
    description:
      "Durable stainless steel safety razor with replaceable blades. Eliminates plastic waste from disposable razors.",
    price: 34.99,
    image: getPlaceholderImage("Bathroom", 16),
    category: "Bathroom",
    tags: ["razor", "stainless steel", "zero waste"],
    inStock: true,
  },
  // Clothing Products
  {
    id: "17",
    name: "Hemp Jogger Pants",
    description: "Comfortable jogger pants made from sustainable hemp and organic cotton blend.",
    price: 49.99,
    image: getPlaceholderImage("Clothing", 17),
    category: "Clothing",
    tags: ["hemp", "pants", "sustainable fashion"],
    inStock: true,
  },
  {
    id: "18",
    name: "Recycled Polyester Jacket",
    description: "Lightweight jacket made from recycled plastic bottles. Water-resistant and breathable.",
    price: 79.99,
    image: getPlaceholderImage("Clothing", 18),
    category: "Clothing",
    tags: ["recycled", "jacket", "outerwear"],
    inStock: true,
  },
  {
    id: "19",
    name: "Organic Linen Shirt",
    description: "Breathable button-up shirt made from 100% organic linen. Perfect for warm weather.",
    price: 59.99,
    image: getPlaceholderImage("Clothing", 19),
    category: "Clothing",
    tags: ["linen", "shirt", "organic"],
    inStock: true,
  },
  {
    id: "20",
    name: "Bamboo Socks Set",
    description: "Pack of 5 pairs of bamboo fiber socks. Naturally antibacterial and moisture-wicking.",
    price: 24.99,
    image: getPlaceholderImage("Clothing", 20),
    category: "Clothing",
    tags: ["bamboo", "socks", "sustainable"],
    inStock: true,
  },
  // Accessories Products
  {
    id: "21",
    name: "Cork Wallet",
    description: "Slim wallet made from sustainable cork. Durable, water-resistant, and vegan.",
    price: 29.99,
    image: getPlaceholderImage("Accessories", 21),
    category: "Accessories",
    tags: ["cork", "wallet", "vegan"],
    inStock: true,
  },
  {
    id: "22",
    name: "Recycled Silver Earrings",
    description: "Handcrafted earrings made from 100% recycled silver with minimalist design.",
    price: 39.99,
    image: getPlaceholderImage("Accessories", 22),
    category: "Accessories",
    tags: ["jewelry", "recycled", "silver"],
    inStock: true,
  },
  {
    id: "23",
    name: "Hemp Sunglasses",
    description: "Stylish sunglasses with frames made from sustainable hemp fiber and recycled materials.",
    price: 69.99,
    image: getPlaceholderImage("Accessories", 23),
    category: "Accessories",
    tags: ["sunglasses", "hemp", "UV protection"],
    inStock: true,
  },
  {
    id: "24",
    name: "Organic Cotton Tote Bag",
    description: "Sturdy tote bag made from organic cotton canvas. Perfect for shopping or daily use.",
    price: 19.99,
    image: getPlaceholderImage("Accessories", 24),
    category: "Accessories",
    tags: ["tote", "organic cotton", "bag"],
    inStock: true,
  },
  // Electronics Products
  {
    id: "25",
    name: "Biodegradable Phone Case",
    description: "Phone case made from plant-based materials that will biodegrade at end of life.",
    price: 24.99,
    image: getPlaceholderImage("Electronics", 25),
    category: "Electronics",
    tags: ["phone case", "biodegradable", "eco-friendly"],
    inStock: true,
  },
  {
    id: "26",
    name: "Solar Bluetooth Speaker",
    description: "Portable Bluetooth speaker with integrated solar panel for eco-friendly charging.",
    price: 79.99,
    image: getPlaceholderImage("Electronics", 26),
    category: "Electronics",
    tags: ["speaker", "solar", "bluetooth"],
    inStock: true,
  },
  {
    id: "27",
    name: "Recycled Laptop Sleeve",
    description: "Protective laptop sleeve made from recycled plastic bottles with soft interior lining.",
    price: 34.99,
    image: getPlaceholderImage("Electronics", 27),
    category: "Electronics",
    tags: ["laptop", "recycled", "sleeve"],
    inStock: true,
  },
  {
    id: "28",
    name: "Eco-Friendly Wireless Earbuds",
    description: "Wireless earbuds made with recycled materials and bamboo charging case.",
    price: 89.99,
    image: getPlaceholderImage("Electronics", 28),
    category: "Electronics",
    tags: ["earbuds", "wireless", "recycled"],
    inStock: true,
  },
  // Home Products
  {
    id: "29",
    name: "Organic Cotton Bedding Set",
    description:
      "Complete bedding set made from 100% GOTS certified organic cotton. Includes sheets, pillowcases, and duvet cover.",
    price: 129.99,
    image: getPlaceholderImage("Home", 29),
    category: "Home",
    tags: ["bedding", "organic cotton", "GOTS certified"],
    inStock: true,
  },
  {
    id: "30",
    name: "Recycled Glass Vase",
    description: "Handblown vase made from 100% recycled glass with unique patterns and colors.",
    price: 39.99,
    image: getPlaceholderImage("Home", 30),
    category: "Home",
    tags: ["vase", "recycled glass", "handmade"],
    inStock: true,
  },
  {
    id: "31",
    name: "Beeswax Candles",
    description: "Set of 3 natural beeswax candles that purify the air and have a subtle honey scent.",
    price: 24.99,
    image: getPlaceholderImage("Home", 31),
    category: "Home",
    tags: ["candles", "beeswax", "natural"],
    inStock: true,
  },
  {
    id: "32",
    name: "Hemp Throw Blanket",
    description: "Cozy throw blanket made from sustainable hemp fiber. Naturally hypoallergenic and durable.",
    price: 69.99,
    image: getPlaceholderImage("Home", 32),
    category: "Home",
    tags: ["blanket", "hemp", "sustainable"],
    inStock: true,
  },
  // Beauty Products
  {
    id: "33",
    name: "Zero Waste Makeup Set",
    description: "Complete makeup set with plastic-free packaging. Includes foundation, blush, and eyeshadow.",
    price: 79.99,
    image: getPlaceholderImage("Beauty", 33),
    category: "Beauty",
    tags: ["makeup", "zero waste", "plastic-free"],
    inStock: true,
  },
  {
    id: "34",
    name: "Organic Face Oil",
    description: "Nourishing face oil made with organic plant oils and packaged in a glass bottle.",
    price: 34.99,
    image: getPlaceholderImage("Beauty", 34),
    category: "Beauty",
    tags: ["face oil", "organic", "skincare"],
    inStock: true,
  },
  {
    id: "35",
    name: "Bamboo Hairbrush",
    description: "Hairbrush with bamboo handle and natural bristles. Gentle on hair and scalp.",
    price: 19.99,
    image: getPlaceholderImage("Beauty", 35),
    category: "Beauty",
    tags: ["hairbrush", "bamboo", "natural"],
    inStock: true,
  },
  {
    id: "36",
    name: "Refillable Deodorant",
    description: "Natural deodorant in a refillable stainless steel container. Aluminum-free and effective.",
    price: 24.99,
    image: getPlaceholderImage("Beauty", 36),
    category: "Beauty",
    tags: ["deodorant", "refillable", "natural"],
    inStock: true,
  },
  // Fitness Products
  {
    id: "37",
    name: "Cork Yoga Block Set",
    description: "Set of 2 yoga blocks made from sustainable cork. Provides stable support for yoga poses.",
    price: 29.99,
    image: getPlaceholderImage("Fitness", 37),
    category: "Fitness",
    tags: ["yoga", "cork", "blocks"],
    inStock: true,
  },
  {
    id: "38",
    name: "Organic Cotton Yoga Strap",
    description: "Durable yoga strap made from organic cotton. Perfect for stretching and improving flexibility.",
    price: 14.99,
    image: getPlaceholderImage("Fitness", 38),
    category: "Fitness",
    tags: ["yoga", "strap", "organic cotton"],
    inStock: true,
  },
  {
    id: "39",
    name: "Sustainable Fitness Ball",
    description: "Exercise ball made from eco-friendly, burst-resistant material. Includes pump.",
    price: 34.99,
    image: getPlaceholderImage("Fitness", 39),
    category: "Fitness",
    tags: ["fitness ball", "exercise", "eco-friendly"],
    inStock: true,
  },
  {
    id: "40",
    name: "Hemp Resistance Bands",
    description:
      "Set of 3 resistance bands made with hemp fiber exterior. Different resistance levels for varied workouts.",
    price: 24.99,
    image: getPlaceholderImage("Fitness", 40),
    category: "Fitness",
    tags: ["resistance bands", "hemp", "workout"],
    inStock: true,
  },
  // Garden Products
  {
    id: "41",
    name: "Compost Bin",
    description: "Countertop compost bin made from bamboo with charcoal filter to eliminate odors.",
    price: 39.99,
    image: getPlaceholderImage("Garden", 41),
    category: "Garden",
    tags: ["compost", "bamboo", "kitchen waste"],
    inStock: true,
  },
  {
    id: "42",
    name: "Biodegradable Plant Pots",
    description: "Set of 12 biodegradable plant pots made from rice husks. Perfect for seedlings.",
    price: 14.99,
    image: getPlaceholderImage("Garden", 42),
    category: "Garden",
    tags: ["plant pots", "biodegradable", "gardening"],
    inStock: true,
  },
  {
    id: "43",
    name: "Organic Seed Kit",
    description: "Complete kit with 10 varieties of organic vegetable and herb seeds. Non-GMO and heirloom varieties.",
    price: 24.99,
    image: getPlaceholderImage("Garden", 43),
    category: "Garden",
    tags: ["seeds", "organic", "gardening"],
    inStock: true,
  },
  {
    id: "44",
    name: "Rainwater Collection System",
    description: "Simple system to collect and store rainwater for garden use. Reduces water consumption.",
    price: 79.99,
    image: getPlaceholderImage("Garden", 44),
    category: "Garden",
    tags: ["rainwater", "conservation", "gardening"],
    inStock: true,
  },
  // Office Products
  {
    id: "45",
    name: "Recycled Paper Notebook Set",
    description: "Set of 3 notebooks made from 100% post-consumer recycled paper with soy-based ink.",
    price: 19.99,
    image: getPlaceholderImage("Office", 45),
    category: "Office",
    tags: ["notebook", "recycled paper", "stationery"],
    inStock: true,
  },
  {
    id: "46",
    name: "Bamboo Desk Organizer",
    description: "Stylish desk organizer made from sustainable bamboo. Multiple compartments for office supplies.",
    price: 34.99,
    image: getPlaceholderImage("Office", 46),
    category: "Office",
    tags: ["desk organizer", "bamboo", "office"],
    inStock: true,
  },
  {
    id: "47",
    name: "Plant-Based Pens",
    description: "Pack of 10 pens made from plant-based materials instead of plastic. Smooth writing experience.",
    price: 12.99,
    image: getPlaceholderImage("Office", 47),
    category: "Office",
    tags: ["pens", "plant-based", "stationery"],
    inStock: true,
  },
  {
    id: "48",
    name: "Upcycled Tire Pencil Case",
    description: "Durable pencil case made from upcycled bicycle inner tubes. Water-resistant and unique.",
    price: 19.99,
    image: getPlaceholderImage("Office", 48),
    category: "Office",
    tags: ["pencil case", "upcycled", "tire"],
    inStock: true,
  },
  // Pet Products
  {
    id: "49",
    name: "Hemp Pet Collar",
    description: "Durable dog collar made from sustainable hemp with brass hardware. Adjustable and washable.",
    price: 24.99,
    image: getPlaceholderImage("Pets", 49),
    category: "Pets",
    tags: ["pet collar", "hemp", "dog"],
    inStock: true,
  },
  {
    id: "50",
    name: "Organic Catnip Toys",
    description: "Set of 3 cat toys filled with organic catnip and made from organic cotton fabric.",
    price: 14.99,
    image: getPlaceholderImage("Pets", 50),
    category: "Pets",
    tags: ["cat toys", "organic", "catnip"],
    inStock: true,
  },
  // Kids Products
  {
    id: "51",
    name: "Wooden Building Blocks",
    description: "Set of 40 wooden building blocks made from FSC-certified wood with non-toxic paint.",
    price: 34.99,
    image: getPlaceholderImage("Kids", 51),
    category: "Kids",
    tags: ["toys", "wooden", "blocks"],
    inStock: true,
  },
  {
    id: "52",
    name: "Organic Cotton Baby Onesies",
    description: "Pack of 3 baby onesies made from GOTS-certified organic cotton. Soft and gentle on sensitive skin.",
    price: 29.99,
    image: getPlaceholderImage("Kids", 52),
    category: "Kids",
    tags: ["baby", "organic cotton", "clothing"],
    inStock: true,
  },
]

export const featuredProducts = [
  products.find((p) => p.id === "1")!,
  products.find((p) => p.id === "5")!,
  products.find((p) => p.id === "13")!,
  products.find((p) => p.id === "26")!,
]

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.category === category)
}

